VariableDefs:
  ExampleNumberVariableName: direct 12
  ExampleStringVariableName: direct ExampleString
  ExampleBooleanVariableName: direct true
  generatedRawFilesFolderPath: direct generated-files
  muml_containerFilePath: direct generated-files/MUML_Container.muml_container
  componentCodeFilesFolderPath: direct deployable-files/fastAndSlowCar_v2
  apiMappingsFolderPath: direct deployable-files/APImappings
  componentsFolderPath: direct deployable-files/fastAndSlowCar_v2/components
  libFolderPath: direct deployable-files/fastAndSlowCar_v2/lib
  messagesFolderPath: direct deployable-files/fastAndSlowCar_v2/messages
  operationsFolderPath: direct deployable-files/fastAndSlowCar_v2/operations
  RTSCsFolderPath: direct deployable-files/fastAndSlowCar_v2/RTSCs
  typesFolderPath: direct deployable-files/fastAndSlowCar_v2/types
  deployableFilesFolderPath: direct deployable-files
  fastCarDesiredVelocity: direct 65
  slowCarDesiredVelocity: direct 55
  usedDriverBoardIdentifierFQBN: direct arduino:avr:mega
  usedCoordinatorBoardIdentifierFQBN: direct arduino:avr:nano
  fastCarCoordinatorECUBoardSerialNumber: direct DummySerialFastCarCoordinator
  fastCarDriverECUBoardSerialNumber: direct DummySerialFastCarDriver
  slowCarCoordinatorECUBoardSerialNumber: direct DummySerialSlowCarCoordinator
  slowCarDriverECUBoardSerialNumber: direct DummySerialSlowCarDriver
  fastCarCoordinatorECUFolderPath: direct deployable-files/fastCarCoordinatorECU
  fastCarCoordinatorECUINOFilePath: direct deployable-files/fastCarCoordinatorECU/fastCarCoordinatorECU.ino
  fastCarCoordinatorECUINOHEXFilePath: direct deployable-files/fastCarCoordinatorECU/CompiledFiles/fastCarCoordinatorECU.ino.hex
  fastCarDriverECUFolderPath: direct deployable-files/fastCarDriverECU
  fastCarDriverECUINOFilePath: direct deployable-files/fastCarDriverECU/fastCarDriverECU.ino
  fastCarDriverECUINOHEXFilePath: direct deployable-files/fastCarDriverECU/CompiledFiles/fastCarDriverECU.ino.hex
  slowCarCoordinatorECUFolderPath: direct deployable-files/slowCarCoordinatorECU
  slowCarCoordinatorECUINOFilePath: direct deployable-files/slowCarCoordinatorECU/slowCarCoordinatorECU.ino
  slowCarCoordinatorECUINOHEXFilePath: direct deployable-files/slowCarCoordinatorECU/CompiledFiles/slowCarCoordinatorECU.ino.hex
  slowCarDriverECUFolderPath: direct deployable-files/slowCarDriverECU
  slowCarDriverECUINOFilePath: direct deployable-files/slowCarDriverECU/slowCarDriverECU.ino
  slowCarDriverECUINOHEXFilePath: direct deployable-files/slowCarDriverECU/CompiledFiles/slowCarDriverECU.ino.hex


StandaloneTransformationAndCodeGenerationsDefs:
  ContainerTransformation:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      middlewareOption: direct MQTT_I2C_CONFIG # Or DDS_CONFIG
      muml_containerFileDestination: from muml_containerFilePath
    out:
      ifSuccessful: ifSuccessful
  ContainerCodeGeneration:
    in:
      muml_containerSourceFile: from muml_containerFilePath
      arduinoContainersDestinationFolder: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
  ComponentCodeGeneration:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      arduinoContainersDestinationFolder: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
  PostProcessingStepsUntilConfig:
    in:
      arduinoContainersPath: direct arduino-containers
      componentCodePath: direct arduino-containers/fastAndSlowCar_v2
      useLocallyStoredConfig_hppFileInsteadOfDownloadingIt: direct true
    out:
      ifSuccessful: ifSuccessful


StandalonePostProcessingSequence:
- direct DeleteFolder:
    in:
      path: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct CopyFolder:
    in:
      sourcePath: from generatedRawFilesFolderPath
      destinationPath: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct CopyFolder has failed!
- direct PostProcessingAdjustIncludes:
    in:
      componentCodePath: from componentCodeFilesFolderPath
      faultyInclude: direct "../components/
      correctInclude: direct "
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustIncludes:
    in:
      componentCodePath: from componentCodeFilesFolderPath
      faultyInclude: direct "../lib/
      correctInclude: direct "
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustIncludes:
    in:
      componentCodePath: from componentCodeFilesFolderPath
      faultyInclude: direct "../messages/
      correctInclude: direct "
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustIncludes:
    in:
      componentCodePath: from componentCodeFilesFolderPath
      faultyInclude: direct "../operations/
      correctInclude: direct "
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustIncludes:
    in:
      componentCodePath: from componentCodeFilesFolderPath
      faultyInclude: direct "../RTSCs/
      correctInclude: direct "
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustIncludes:
    in:
      componentCodePath: from componentCodeFilesFolderPath
      faultyInclude: direct "../types/
      correctInclude: direct "
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingMoveIncludeBefore_ifdef__cplusplus:
    in:
      componentsPath: from componentsFolderPath
      targetInclude: direct "clock.h"
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsWhitelist:
    in:
      sourceFolder: from componentsFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct CarCoordinatorECU
      whitelist: direct coordinatorComponent_Interface.h, coordinatorComponent.c
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsAndExcept:
    in:
      sourceFolder: from componentsFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct CarDriverECU
      except: direct coordinatorComponent_Interface.h, coordinatorComponent.c
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsAndExcept:
    in:
      sourceFolder: from libFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct ECU
      except: direct clock.h, standardTypes.h
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsAndExcept:
    in:
      sourceFolder: from messagesFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct ECU
      except: direct none
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsAndExcept:
    in:
      sourceFolder: from operationsFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct CarDriverECU
      except: direct none
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsWhitelist:
    in:
      sourceFolder: from RTSCsFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct CarCoordinatorECU
      whitelist: direct coordinatorCoordinatorComponentStateChart.c
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsWhitelist:
    in:
      sourceFolder: from RTSCsFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct CarDriverECU
      whitelist: direct courseControlCourseControlComponentStateChart.c
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyFolderContentsToECUsAndExcept:
    in:
      sourceFolder: from typesFolderPath
      destinationFolder: from deployableFilesFolderPath
      ecuEnding: direct ECU
      except: direct none
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from fastCarDriverECUFolderPath
      fileName: direct CI_FRONTDISTANCESENSORFDISTANCESENSORdistancePortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *distance = SimpleHardwareController_DistanceSensor_GetDistanceToClosestMm(0);
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from fastCarDriverECUFolderPath
      fileName: direct CI_REARDISTANCESENSORFDISTANCESENSORdistancePortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *distance = SimpleHardwareController_DistanceSensor_GetDistanceToClosestMm(1);
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from fastCarDriverECUFolderPath
      fileName: direct CI_DRIVECONTROLLERFDRIVECONTROLLERvelocityPortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *velocity = SimpleHardwareController_DriveController_GetSpeed();
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from fastCarDriverECUFolderPath
      fileName: direct CI_DRIVECONTROLLERFDRIVECONTROLLERanglePortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *angle = SimpleHardwareController_DriveController_GetAngle();
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from slowCarDriverECUFolderPath
      fileName: direct CI_FRONTDISTANCESENSORSDISTANCESENSORdistancePortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *distance = SimpleHardwareController_DistanceSensor_GetDistanceToClosestMm(0);
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from slowCarDriverECUFolderPath
      fileName: direct CI_REARDISTANCESENSORSDISTANCESENSORdistancePortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *distance = SimpleHardwareController_DistanceSensor_GetDistanceToClosestMm(1);
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from slowCarDriverECUFolderPath
      fileName: direct CI_DRIVECONTROLLERSDRIVECONTROLLERvelocityPortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *velocity = SimpleHardwareController_DriveController_GetSpeed();
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAdjustAPIMappingFile:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from slowCarDriverECUFolderPath
      fileName: direct CI_DRIVECONTROLLERSDRIVECONTROLLERanglePortaccessCommand.c
      library: direct SimpleHardwareController_Connector.h
      instruction: direct *angle = SimpleHardwareController_DriveController_GetAngle();
    out:
      ifSuccessful: ifSuccessful
- direct CopyFiles:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from fastCarDriverECUFolderPath
      files: direct CI_FRONTDISTANCESENSORFDISTANCESENSORdistancePortaccessCommand.h,
        CI_DRIVECONTROLLERFDRIVECONTROLLERvelocityPortaccessCommand.h, CI_DRIVECONTROLLERFDRIVECONTROLLERanglePortaccessCommand.h,
        CI_REARDISTANCESENSORFDISTANCESENSORdistancePortaccessCommand.h
    out:
      ifSuccessful: ifSuccessful
- direct CopyFiles:
    in:
      sourceFolder: from apiMappingsFolderPath
      destinationFolder: from slowCarDriverECUFolderPath
      files: direct CI_FRONTDISTANCESENSORSDISTANCESENSORdistancePortaccessCommand.h,
        CI_DRIVECONTROLLERSDRIVECONTROLLERvelocityPortaccessCommand.h, CI_DRIVECONTROLLERSDRIVECONTROLLERanglePortaccessCommand.h,
        CI_REARDISTANCESENSORSDISTANCESENSORdistancePortaccessCommand.h
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingCopyLocalConfig_hppToCarDeriverECUs:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingAddHALPartsIntoCarDriverInoFiles:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingFillOutMethodStubs:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct PostProcessingStateChartValues:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      ECUName: direct fastCarDriverECU
      distanceLimit: direct 40
      desiredVelocity: from fastCarDesiredVelocity
      slowVelocity: direct 0
      laneDistance: direct 70
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStateChartValues for fastCarDriverECU has failed!
- direct PostProcessingStateChartValues:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      ECUName: direct slowCarDriverECU
      distanceLimit: direct 40
      desiredVelocity: from slowCarDesiredVelocity
      slowVelocity: direct 0
      laneDistance: direct 70
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStateChartValues for slowCarDriverECU has failed!
- direct DeleteFolder:
    in:
      path: from apiMappingsFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct DeleteFolder:
    in:
      path: from componentCodeFilesFolderPath
    out:
      ifSuccessful: ifSuccessful


PipelineSequence:
- direct DeleteFolder:
    in:
      path: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct DeleteFolder:
    in:
      path: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- from StandaloneTransformationAndCodeGenerationsDefs: ContainerTransformation
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ContainerTransformation has failed!
- from StandaloneTransformationAndCodeGenerationsDefs: ContainerCodeGeneration
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ContainerCodeGeneration has failed!
- from StandaloneTransformationAndCodeGenerationsDefs: ComponentCodeGeneration
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ComponentCodeGeneration has failed!
- from StandalonePostProcessingSequence: all
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoFile: from fastCarCoordinatorECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for fastCarCoordinatorECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoFile: from fastCarDriverECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for fastCarDriverECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoFile: from slowCarCoordinatorECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for slowCarCoordinatorECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoFile: from slowCarDriverECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for slowCarDriverECU has failed!
