VariableDefs:
  ExampleNumberVariableName: direct 12
  ExampleStringVariableName: direct ExampleString
  ExampleBooleanVariableName: direct true
  generatedRawFilesFolderPath: direct generated-files
  muml_containerFilePath: direct generated-files/MUML_Container.muml_container
  componentCodeFilesFolderPath: direct deployable-files/fastAndSlowCar_v2
  apiMappingsFolderPath: direct deployable-files/APImappings
  deployableFilesFolderPath: direct deployable-files
  usedDriverBoardIdentifierFQBN: direct arduino:avr:mega
  usedCoordinatorBoardIdentifierFQBN: direct arduino:avr:nano
  fastCarCoordinatorECUFolderPath: direct deployable-files/fastCarCoordinatorECU
  fastCarCoordinatorECUINOFilePath: direct deployable-files/fastCarCoordinatorECU/fastCarCoordinatorECU.ino
  fastCarCoordinatorECUBoardSerialNumber: direct DummySerialFastCarCoordinator
  fastCarDriverECUFolderPath: direct deployable-files/fastCarDriverECU
  fastCarDriverECUINOFilePath: direct deployable-files/fastCarDriverECU/fastCarDriverECU.ino
  fastCarDriverECUBoardSerialNumber: direct DummySerialFastCarDriver
  slowCarCoordinatorECUFolderPath: direct deployable-files/slowCarCoordinatorECU
  slowCarCoordinatorECUINOFilePath: direct deployable-files/slowCarCoordinatorECU/slowCarCoordinatorECU.ino
  slowCarCoordinatorECUBoardSerialNumber: direct DummySerialSlowCarCoordinator
  slowCarDriverECUFolderPath: direct deployable-files/slowCarDriverECU
  slowCarDriverECUINOFilePath: direct deployable-files/slowCarDriverECU/slowCarDriverECU.ino
  slowCarDriverECUBoardSerialNumber: direct DummySerialSlowCarDriver


StandaloneUsageDefs:
  ContainerTransformation:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      middlewareOption: direct MQTT_I2C_CONFIG # Or DDS_CONFIG
      muml_containerFileDestination: direct container-models/MUML_Container.muml_container
    out:
      ifSuccessful: ifSuccessful
  ContainerCodeGeneration:
    in:
      muml_containerSourceFile: direct container-models/MUML_Container.muml_container
      arduinoContainersDestinationFolder: direct arduino-containers
    out:
      ifSuccessful: ifSuccessful
  ComponentCodeGeneration:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      arduinoContainersDestinationFolder: direct arduino-containers
    out:
      ifSuccessful: ifSuccessful
  PostProcessingStepsUntilConfig:
    in:
      arduinoContainersPath: direct arduino-containers
      componentCodePath: direct arduino-containers/fastAndSlowCar_v2
      useLocallyStoredConfig_hppFileInsteadOfDownloadingIt: direct true
    out:
      ifSuccessful: ifSuccessful


PipelineSequence:
- direct DeleteFolder:
    in:
      path: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct DeleteFolder:
    in:
      path: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct ContainerTransformation:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      middlewareOption: direct MQTT_I2C_CONFIG # Or DDS_CONFIG
      muml_containerFileDestination: from muml_containerFilePath
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ContainerTransformation has failed!
- direct ContainerCodeGeneration:
    in:
      muml_containerSourceFile: from muml_containerFilePath
      arduinoContainersDestinationFolder: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ContainerCodeGeneration has failed!
- direct ComponentCodeGeneration:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      arduinoContainersDestinationFolder: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ComponentCodeGeneration has failed!
- direct CopyFolder:
    in:
      sourcePath: from generatedRawFilesFolderPath
      destinationPath: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct CopyFolder has failed!
- direct PostProcessingStepsUntilConfig:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      componentCodePath: from componentCodeFilesFolderPath
      useLocallyStoredConfig_hppFileInsteadOfDownloadingIt: direct true
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStepsUntilConfig has failed!
- direct PostProcessingStateChartValues:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      ECUName: direct fastCarDriverECU
      distanceLimit: direct 1
      desiredVelocity: direct 2
      slowVelocity: direct 3
      laneDistance: direct 4
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStateChartValues for fastCarDriverECU has failed!
- direct PostProcessingStateChartValues:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      ECUName: direct slowCarDriverECU
      distanceLimit: direct 1
      desiredVelocity: direct 2
      slowVelocity: direct 3
      laneDistance: direct 4
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStateChartValues for slowCarDriverECU has failed!
- direct DeleteFolder:
    in:
      path: from apiMappingsFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct DeleteFolder:
    in:
      path: from componentCodeFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoFile: from fastCarCoordinatorECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for fastCarCoordinatorECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoFile: from fastCarDriverECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for fastCarDriverECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoFile: from slowCarCoordinatorECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for slowCarCoordinatorECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoFile: from slowCarDriverECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for slowCarDriverECU has failed!
- direct PopupWindowMessage:
    in:
      condition: direct true
      message: direct Pipeline execution completed!
