VariableDefs:
  ExampleNumberVariableName: direct 12
  ExampleStringVariableName: direct ExampleString
  ExampleBooleanVariableName: direct true
  generatedRawFilesFolderPath: direct generated-files
  muml_containerFilePath: direct generated-files/MUML_Container.muml_container
  componentCodeFilesFolderPath: direct deployable-files/fastAndSlowCar_v2
  apiMappingsFolderPath: direct deployable-files/APImappings
  deployableFilesFolderPath: direct deployable-files
  fastCarDesiredVelocity: direct 65
  slowCarDesiredVelocity: direct 55
  usedDriverBoardIdentifierFQBN: direct arduino:avr:mega
  usedCoordinatorBoardIdentifierFQBN: direct arduino:avr:mega # nano
  fastCarCoordinatorECUBoardSerialNumber: direct 8593731333735141A130
  fastCarDriverECUBoardSerialNumber: direct 8593731333735141A130
  slowCarCoordinatorECUBoardSerialNumber: direct 8593731333735141A130
  slowCarDriverECUBoardSerialNumber: direct 8593731333735141A130
  fastCarCoordinatorECUFolderPath: direct deployable-files/fastCarCoordinatorECU
  fastCarCoordinatorECUINOFilePath: direct deployable-files/fastCarCoordinatorECU/fastCarCoordinatorECU.ino
  fastCarCoordinatorECUINOHEXFilePath: direct deployable-files/fastCarCoordinatorECU/CompiledFiles/fastCarCoordinatorECU.ino.hex
  fastCarDriverECUFolderPath: direct deployable-files/fastCarDriverECU
  fastCarDriverECUINOFilePath: direct deployable-files/fastCarDriverECU/fastCarDriverECU.ino
  fastCarDriverECUINOHEXFilePath: direct deployable-files/fastCarDriverECU/CompiledFiles/fastCarDriverECU.ino.hex
  slowCarCoordinatorECUFolderPath: direct deployable-files/slowCarCoordinatorECU
  slowCarCoordinatorECUINOFilePath: direct deployable-files/slowCarCoordinatorECU/slowCarCoordinatorECU.ino
  slowCarCoordinatorECUINOHEXFilePath: direct deployable-files/slowCarCoordinatorECU/CompiledFiles/slowCarCoordinatorECU.ino.hex
  slowCarDriverECUFolderPath: direct deployable-files/slowCarDriverECU
  slowCarDriverECUINOFilePath: direct deployable-files/slowCarDriverECU/slowCarDriverECU.ino
  slowCarDriverECUINOHEXFilePath: direct deployable-files/slowCarDriverECU/CompiledFiles/slowCarDriverECU.ino.hex


StandaloneTransformationAndCodeGenerationsDefs:
  ContainerTransformation:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      middlewareOption: direct MQTT_I2C_CONFIG # Or DDS_CONFIG
      muml_containerFileDestination: from muml_containerFilePath
    out:
      ifSuccessful: ifSuccessful
  ContainerCodeGeneration:
    in:
      muml_containerSourceFile: from muml_containerFilePath
      arduinoContainersDestinationFolder: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
  ComponentCodeGeneration:
    in:
      roboCar_mumlSourceFile: direct model/roboCar.muml
      arduinoContainersDestinationFolder: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
  PostProcessingStepsUntilConfig:
    in:
      arduinoContainersPath: direct arduino-containers
      componentCodePath: direct arduino-containers/fastAndSlowCar_v2
      useLocallyStoredConfig_hppFileInsteadOfDownloadingIt: direct true
    out:
      ifSuccessful: ifSuccessful


StandalonePostProcessingSequence:
- direct DeleteFolder:
    in:
      path: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct CopyFolder:
    in:
      sourcePath: from generatedRawFilesFolderPath
      destinationPath: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct CopyFolder has failed!
- direct PostProcessingStepsUntilConfig:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      componentCodePath: from componentCodeFilesFolderPath
      useLocallyStoredConfig_hppFileInsteadOfDownloadingIt: direct true
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStepsUntilConfig has failed!
- direct PostProcessingStateChartValues:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      ECUName: direct fastCarDriverECU
      distanceLimit: direct 40
      desiredVelocity: from fastCarDesiredVelocity
      slowVelocity: direct 0
      laneDistance: direct 70
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStateChartValues for fastCarDriverECU has failed!
- direct PostProcessingStateChartValues:
    in:
      arduinoContainersPath: from deployableFilesFolderPath
      ECUName: direct slowCarDriverECU
      distanceLimit: direct 40
      desiredVelocity: from slowCarDesiredVelocity
      slowVelocity: direct 0
      laneDistance: direct 70
    out:
      ifSuccessful: ifSuccessful
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct PostProcessingStateChartValues for slowCarDriverECU has failed!
- direct DeleteFolder:
    in:
      path: from apiMappingsFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct DeleteFolder:
    in:
      path: from componentCodeFilesFolderPath
    out:
      ifSuccessful: ifSuccessful


PipelineSequence:
- direct DeleteFolder:
    in:
      path: from generatedRawFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- direct DeleteFolder:
    in:
      path: from deployableFilesFolderPath
    out:
      ifSuccessful: ifSuccessful
- from StandaloneTransformationAndCodeGenerationsDefs: ContainerTransformation
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ContainerTransformation has failed!
- from StandaloneTransformationAndCodeGenerationsDefs: ContainerCodeGeneration
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ContainerCodeGeneration has failed!
- from StandaloneTransformationAndCodeGenerationsDefs: ComponentCodeGeneration
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct ComponentCodeGeneration has failed!
- from StandalonePostProcessingSequence: all
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoFile: from fastCarCoordinatorECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for fastCarCoordinatorECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoFile: from fastCarDriverECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for fastCarDriverECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoFile: from slowCarCoordinatorECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for slowCarCoordinatorECU has failed!
- direct Compile:
    in:
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoFile: from slowCarDriverECUINOFilePath
      saveCompiledFilesNearby: direct true
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Compile for slowCarDriverECU has failed!
- direct LookupBoardBySerialNumber:
    in:
      boardSerialNumber: from fastCarCoordinatorECUBoardSerialNumber
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
    out:
      ifSuccessful: ifSuccessful
      foundPortAddress: foundPortAddress
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct LookupBoardBySerialNumber for fastCarCoordinatorECU has failed!
- direct Upload:
    in:
      portAddress: from foundPortAddress
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoOrHexFile: from fastCarCoordinatorECUINOHEXFilePath
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Upload for fastCarCoordinatorECU has failed!
- direct LookupBoardBySerialNumber:
    in:
      boardSerialNumber: from fastCarDriverECUBoardSerialNumber
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
    out:
      ifSuccessful: ifSuccessful
      foundPortAddress: foundPortAddress
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct LookupBoardBySerialNumber for fastCarDriverECU has failed!
- direct Upload:
    in:
      portAddress: from foundPortAddress
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoOrHexFile: from fastCarDriverECUINOHEXFilePath
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Upload for fastCarDriverECU has failed!
- direct LookupBoardBySerialNumber:
    in:
      boardSerialNumber: from slowCarCoordinatorECUBoardSerialNumber
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
    out:
      ifSuccessful: ifSuccessful
      foundPortAddress: foundPortAddress
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct LookupBoardBySerialNumber for slowCarCoordinatorECU has failed!
- direct Upload:
    in:
      portAddress: from foundPortAddress
      boardTypeIdentifierFQBN: from usedCoordinatorBoardIdentifierFQBN
      targetInoOrHexFile: from slowCarCoordinatorECUINOHEXFilePath
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Upload for slowCarCoordinatorECU has failed!
- direct LookupBoardBySerialNumber:
    in:
      boardSerialNumber: from slowCarDriverECUBoardSerialNumber
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
    out:
      ifSuccessful: ifSuccessful
      foundPortAddress: foundPortAddress
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct LookupBoardBySerialNumber for slowCarDriverECU has failed!
- direct Upload:
    in:
      portAddress: from foundPortAddress
      boardTypeIdentifierFQBN: from usedDriverBoardIdentifierFQBN
      targetInoOrHexFile: from slowCarDriverECUINOHEXFilePath
    out:
      ifSuccessful: ifSuccessful
      resultMessage: resultMessage
- direct OnlyContinueIfFulfilledElseAbort:
    in:
      condition: from ifSuccessful
      message: direct Upload for slowCarDriverECU has failed!
- direct PopupWindowMessage:
    in:
      condition: direct true
      message: direct Pipeline execution completed!
