	/**
 * @file 
 * @author generated by Fraunhofer IEM
 * @brief Specification of Component of Type: PowerTrain
 * @details This files contains a description of the PowerTrain in form of the PowerTrainComponent
 * 			and all methods which can be executed on an Instance of this Component
 */
		#ifndef POWERTRAINCOMPONENT_Interface_H_
		#define POWERTRAINCOMPONENT_Interface_H_

#include "clock.h"

#ifdef __cplusplus
  extern "C" {
#endif		// Library
	#include "standardTypes.h"
	#include "customTypes.h"
	#include "port.h"
	#include "Debug.h"
			/*****
 			 *
 			 *  Forward Delcaration of Container Functions
 			 *
 			 */		
			
					bool_T MCC_PowerTrainComponent_velocity_recv_value(Port* p, int32_T* value);
					bool_T MCC_PowerTrainComponent_velocity_exists_value(Port* p);
			
			
	
			/*****
 			 *
 			 *  Component Functions
 			 *
 			 */
			/**
			 * @file 
			 * @author generated by Fraunhofer IEM 
			 * @brief Specification of Component of Type: PowerTrain
			 * @details This files contains a description of the PowerTrain in form of the PowerTrainComponent
			 * 			and all methods which can be executed on an Instance of this Component
			 */
				
						/**
						 * @brief Forward Declaration of the struct PowerTrainComponent
						 */
							typedef struct PowerTrainComponent PowerTrainComponent;
						
						/**
						*  
						* @brief Description for a ComponentInstance of Type: PowerTrain
						* @details This struct describes a specific Component Instances which is typed over the Component: PowerTrain
						*/
						struct PowerTrainComponent {
						
								uint8_T ID;	
						
						
							
										Port velocityPort; /**< A  Component's Port: velocity */
										Clock velocityPortClock; /**< A  Hybrid/ Continuous Port's Clock: velocityPortClock */
								
									void (*velocityPortAccessFunction) (int32_T*); /**access function pointer for continuous port */
									/*FIXME: Add InitFunction and Destory Funcion */
						
									int32_T velocity; /*A Ports Data Variable*/
								
								
						
								PowerTrainComponent * next;/**< A Pointer to the next component part, if this component ist part of a multipart in the CIC */
								
							};
					
						/**
						* @brief This Methodes intializes the Component: PowerTrain
						* @details All struct members of the struct PowerTrainComponent are initialized
						* 
						* @param component The PowerTrainComponent to be initialized
						*/	
							void PowerTrainComponent_initialize(PowerTrainComponent* component);
				
						/**
						* @brief Creates a Instance of the Component: PowerTrain
						* @details Allocates Memory for the struct PowerTrainComponent
						* @return A Pointer to the new created PowerTrainComponent
						*/
							PowerTrainComponent PowerTrainComponent_create();
				
						/**
						 * @brief Destroys a Component: PowerTrain
						 * @details Frees the Memory for the struct PowerTrainComponent
						 * 
						* @param component The specific PowerTrainComponent to be destroyed
						 */
							void PowerTrainComponent_destroy(PowerTrainComponent* component);
						
						/**
						* @brief Executes the next Step of the behavior an Instance of the Component: PowerTrain
						* @details The behavior of the Component:  PowerTrain is executed.
						*			
						* @param component The PowerTrainComponent whose behavior shall be checked
						*/
							void PowerTrainComponent_processStep(PowerTrainComponent* component);
				
			
			
			
			
						/*Getter and Setter for Sending Values of Hybrid/Continuous ports*/
								bool_T getterOf_velocity(Port* velocityPort, int32_T* velocity);/**< A Pointer to the getter function of the port: velocity */
					
						
		

	





#ifdef __cplusplus
  }
#endif
		#endif /* POWERTRAINCOMPONENT_Interface_H_ */
